version: '3.8'

services:
  bored-tap:
    container_name: bored-tap
    build: .
    ports:
      - "8000:8000"
    env_file:
      - .env
    depends_on:
      - db
    # command: sh -c "uvicorn main:app --reload --port=8000 --host=0.0.0.0"

  db:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - ./data:/data/db
    # env_file:
    #   - .env
